image:
  repository: 160885263219.dkr.ecr.us-east-1.amazonaws.com/sampleapplication
  tag: "7a43a8a70f8e17c9dd1d186d6a1850d67016659f"
  pullPolicy: IfNotPresent
  imagePullSecrets: []

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

containerPort: 80    
