image:
  repository: 160885263219.dkr.ecr.us-east-1.amazonaws.com/sampleapplication
  tag: "18d2540caf6698c6cf790468367e546a0d0bfba0"
  pullPolicy: IfNotPresent
  imagePullSecrets: []

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

containerPort: 80    
